remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

title: GitHub Pages Test
description: Testing a structured Jekyll site

url: "https://johnrenner94.github.io"
baseurl: "/pages-test"

search_enabled: true
